name: Bitcoin Emir Takip
on:
  schedule:
    # Her 4 saatte bir çalıştır (çok sık istek yapmamak için)
    - cron: '0 */4 * * *'
  
  # Manuel tetikleme için workflow_dispatch ekleyin
  workflow_dispatch:
# İzinleri açıkça belirtin
permissions:
  contents: write
jobs:
  collect-orders:
    runs-on: ubuntu-latest
    
    steps:
    - name: Kodu indir
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Tam git geçmişini al
      
    - name: Python 3.10 kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Emir defteri verilerini kazı
      run: python main.py
      continue-on-error: true  # Hata olsa bile devam et
    
    - name: Değişiklikleri GitHub'a kaydet
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/
        git diff --quiet && git diff --staged --quiet || git commit -m "Otomatik veri güncelleme: $(date)"
        git push
