name: Bitcoin Emir Takip

on:
  schedule:
    # Her 2 saatte bir çalıştır
    - cron: '0 */2 * * *'
  
  # Manuel tetikleme için workflow_dispatch ekleyin
  workflow_dispatch:

# İzinleri açıkça belirtin
permissions:
  contents: write

jobs:
  collect-orders:
    runs-on: ubuntu-latest
    
    steps:
    - name: Kodu indir
      uses: actions/checkout@v3
      
    - name: Python 3.10 kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Emir defteri verilerini kazı
      run: python main.py
    
    - name: Değişiklikleri GitHub'a kaydet
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/
        git diff --quiet && git diff --staged --quiet || git commit -m "Otomatik veri güncelleme: $(date)"
        git push
